---
abstract: 'Log queries for later analysis.'
author:
  - 'Cory G Watson, C<< <gphat at cpan.org> >>'
distribution_type: module
generated_by: 'Module::Install version 0.79'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: DBIx-Class-QueryLog
no_index:
  directory:
    - inc
    - t
requires:
  Class::Accessor: 0
  DBIx::Class: 0
  Test::More: 0
  Time::HiRes: 0
resources:
  license: http://dev.perl.org/licenses/
version: 1.1.5
